### ISSUE TITLE
Decimal changes not being processed

### ISSUE THREAD

**Issue by dkho87** [JAM-IT-NL/MendixBootstrapInputAddons#2]
There seem to be some problems with Decimal attributes. Specifically:

- I enter 123 as input and hit save; everything is fine.
- If I now decide to change 123 to 123,45 and hit save; the change is not saved.
- I create a new instance of the object and enter a value of 123,45; the value is not stored at all.

I've tested this in a separate project and can reproduce this in Mx 6.5.1.

For some reason attaching the project file (zipped) isn't currently working. Let me know if you need it.

**Comment by martijnraats** [comment]
This was fixed in the current version. I released it. You can download it here: https://github.com/JAM-IT-NL/MendixBootstrapInputAddons/releases/tag/v1.0.3
