### ISSUE TITLE
Passing enclosing dataviews context object to Bootstrap input text box

### ISSUE THREAD

**Issue by harishmegharaj** [JAM-IT-NL/MendixBootstrapInputAddons#4]
How to pass enclosing dataviews context object to this input text box.
I have a microflow which accepts a input parameter and i want to call that microflow by configuring it in the "onChangeEvent" of this "bootstrapInputAddon". This input parameter which i want to pass is of the "dataview" where i have embedded the "MendixBootstrapInputAddon".

can you please help in,  configuring this input box to pass the parameter

**Comment by martijnraats** [comment]
What you are describing is possible with this widget. I think it's best you put your question on the Mendix forum.

**Comment by harishmegharaj** [comment]
Thanks, will communicate same in Mendix forum.

Regards,
Harish

**Comment by harishmegharaj** [comment]
In our case or normal mendix input text box accepts "multi level data view" (one data view inside another). But in this bootstrap input text box it accepts "data view at only one level", if we have 2 levels it throws an error as stated earlier.
To resolve this problem, we created a new microflow which merged 2 dataview into a single one. 
It would be helpful if you create a multi level data view structure instead of current one, so that it is helpful for others which will avoid creation of new microflow.

**Comment by martijnraats** [comment]
Unfortunately what you ask is not possible incustom widget developing. I asked this before in this thread: https://forum.mendixcloud.com/link/questions/88544
