### ISSUE TITLE
RegEx shows "Ongeldig nummer" instead of invalid number

### ISSUE THREAD

**Issue by harishmegharaj** [JAM-IT-NL/MendixBootstrapInputAddons#5]
Hi,
   When I use input text box with regex it shows proper entered error message i.e. "Invalid number". Now, if the input text box already has some pre-populated value ( i.e. Edit field). It throws error message in different language "Ongeldig numme".
  Is it a bug? Or do we need to do some configuration changes?

**Comment by martijnraats** [comment]
I fixed this in release V3.2.1
