### ISSUE TITLE
Question: Why does this requires 7.9.0?

### ISSUE THREAD

**Issue by Vilscon** [JAM-IT-NL/MendixBootstrapInputAddons#6]
Our project is running on 7.7.1 and this plugin is the only reason why we consider upgrading for now. Using `input-form` and `input-form-group` for the input addon is very nice, but a validation error stretches it. We have yet to find a solution for this, aside from this plugin.

So partially I am wondering why this requires 7.9.0 and on the other hand perhaps you can tell if this is solvable without this plugin for now?

So not really an issue, but I couldn't find a question form. :)

**Comment by martijnraats** [comment]
The widget is only developed/tested with the Mendix version we are using for our own projects (which most of the time is the latest). This is just a cost/time issue for ourself.

You can use older versions of the widget that work with your Mendix version by downloading them from https://github.com/JAM-IT-NL/MendixBootstrapInputAddons/releases.

I didn't test it, but it could be very possible that the latest version of this widget will also work with 7.7.1.
